/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0 */

#ifndef _Included_com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
#define _Included_com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    getAlgorithmVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_getAlgorithmVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    getAlgorithmContextFromNative
 * Signature: ()Lcom/algorithm/v1_1_0/AlgorithmClassContext;
 */
JNIEXPORT jobject JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_getAlgorithmContextFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    resetAlgorithmContext
 * Signature: (Lcom/algorithm/v1_1_0/AlgorithmClassContext;)V
 */
JNIEXPORT void JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_resetAlgorithmContext
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    processAlgorithmConvert
 * Signature: (Lcom/algorithm/v1_1_0/AlgorithmClassContext;IDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_processAlgorithmConvert
  (JNIEnv *, jclass, jobject, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    getJsonAlgorithmContext
 * Signature: (Lcom/algorithm/v1_1_0/AlgorithmClassContext;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_getJsonAlgorithmContext
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    setJsonAlgorithmContext
 * Signature: (Lcom/algorithm/v1_1_0/AlgorithmClassContext;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_setJsonAlgorithmContext
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    getAGPFunction
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_getAGPFunction
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    getGEFunction
 * Signature: ([F)F
 */
JNIEXPORT jfloat JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_getGEFunction
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    getIDRFunction
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_getIDRFunction
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    getIQRFunction
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_getIQRFunction
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    getCMFunction
 * Signature: ([F)F
 */
JNIEXPORT jfloat JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_getCMFunction
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    getLBGRFunction
 * Signature: ([FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_getLBGRFunction
  (JNIEnv *, jclass, jfloatArray, jfloat);

/*
 * Class:     com_algorithm_v1_1_0_NativeAlgorithmLibraryV1_1_0
 * Method:    getHBGRFunction
 * Signature: ([FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_algorithm_v1_11_10_NativeAlgorithmLibraryV1_11_10_getHBGRFunction
  (JNIEnv *, jclass, jfloatArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
